-- MySQL Script generated by MySQL Workbench
-- Mon Nov  9 16:08:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nutri
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nutri
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nutri` DEFAULT CHARACTER SET utf8 ;
USE `nutri` ;

-- -----------------------------------------------------
-- Table `nutri`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`tipousuario` (
  `idtipousuario` INT NOT NULL AUTO_INCREMENT,
  `nometipousuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipousuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `idtipousuario` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_tipousuario1_idx` (`idtipousuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipousuario1`
    FOREIGN KEY (`idtipousuario`)
    REFERENCES `nutri`.`tipousuario` (`idtipousuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `datanasc` DATE NOT NULL,
  `idade` INT NOT NULL,
  `estadocivil` VARCHAR(45) NOT NULL,
  `ocupacao` VARCHAR(45) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `rg` INT NOT NULL,
  `telefone` INT(12) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idpessoa`),
  INDEX `fk_pessoa_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `nutri`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`habitoscotidiano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`habitoscotidiano` (
  `idhabitos_cotidiano` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `dataavaliacao` DATE NOT NULL,
  `restricaoalimentar` VARCHAR(3) NOT NULL,
  `descrestricao` VARCHAR(200) NULL,
  `ingbebidaalcool` VARCHAR(3) NOT NULL,
  `freqbebidaalcool` VARCHAR(150) NULL,
  `fumante` VARCHAR(3) NOT NULL,
  `freqfumo` VARCHAR(150) NULL,
  `qdtemoradorescasa` INT NOT NULL,
  `quemfazcompra` VARCHAR(150) NOT NULL,
  `localcompra` VARCHAR(150) NOT NULL,
  `freqcompra` VARCHAR(150) NOT NULL,
  `litrosoleo` INT NOT NULL,
  `quilossal` INT NOT NULL,
  `qualidadesono` VARCHAR(3) NOT NULL,
  `horassono` INT NOT NULL,
  `observacaosono` VARCHAR(150) NOT NULL,
  `praticaexercfisico` VARCHAR(3) NOT NULL,
  `exerciciofisico` VARCHAR(150) NOT NULL,
  `freqexercfisico` INT NOT NULL,
  `tempoexercfisico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idhabitos_cotidiano`),
  INDEX `fk_habitoscotidiano_pessoa1_idx` (`idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_habitoscotidiano_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `nutri`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`patologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`patologia` (
  `idpatologia` INT NOT NULL AUTO_INCREMENT,
  `nomepatologia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpatologia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`historicomedico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`historicomedico` (
  `idhistoricomedico` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `usomedicamentos` TINYINT NOT NULL,
  `descmedicamentos` VARCHAR(200) NULL,
  `horariomedicamentos` VARCHAR(150) NULL,
  `historicofamiliar` VARCHAR(500) NULL,
  PRIMARY KEY (`idhistoricomedico`),
  INDEX `fk_historicomedico_pessoa1_idx` (`idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_historicomedico_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `nutri`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`exames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`exames` (
  `idexames` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `nomeexame` VARCHAR(45) NOT NULL,
  `dataexame` DATE NOT NULL,
  `referencia` VARCHAR(150) NOT NULL,
  `alteracao` VARCHAR(150) NOT NULL,
  `arqexame` BLOB NULL,
  PRIMARY KEY (`idexames`),
  INDEX `fk_exames_pessoa1_idx` (`idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_exames_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `nutri`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`avaliacaoclinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`avaliacaoclinica` (
  `idavaliacaoclinica` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `apetite` VARCHAR(45) NOT NULL,
  `mastigacao` VARCHAR(45) NOT NULL,
  `tempomastigacao` VARCHAR(150) NOT NULL,
  `habitointestinal` VARCHAR(45) NOT NULL,
  `frequenciaevacuacao` VARCHAR(150) NOT NULL,
  `usodelaxante` TINYINT NOT NULL,
  `sanguefezes` TINYINT NOT NULL,
  `temposaguefezes` VARCHAR(150) NOT NULL,
  `habitourinario` VARCHAR(250) NOT NULL,
  `ingestaohidricadiaria` VARCHAR(200) NOT NULL,
  `corurina` VARCHAR(45) NOT NULL,
  `ultimamenstruacao` VARCHAR(200) NULL,
  `tpm` VARCHAR(45) NULL,
  `clicomenstrualregular` VARCHAR(3) NULL,
  `contraceptivo` VARCHAR(200) NULL,
  `colica` VARCHAR(3) NULL,
  `lactante` VARCHAR(3) NULL,
  `menopausa` VARCHAR(3) NULL,
  PRIMARY KEY (`idavaliacaoclinica`),
  INDEX `fk_avaliacaoclinica_pessoa1_idx` (`idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacaoclinica_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `nutri`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`habitosalimentares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`habitosalimentares` (
  `idhabitosalimentares` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `suplementos` VARCHAR(300) NULL,
  `alergia` VARCHAR(300) NULL,
  `intolerancia` VARCHAR(300) NULL,
  `aversao` VARCHAR(300) NULL,
  PRIMARY KEY (`idhabitosalimentares`),
  INDEX `fk_habitosalimentares_pessoa1_idx` (`idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_habitosalimentares_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `nutri`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`recordatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`recordatorio` (
  `idrecordatorio` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `data` DATE NOT NULL,
  `tipodia` VARCHAR(45) NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  `alimento` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idrecordatorio`),
  INDEX `fk_recordatorio_pessoa1_idx` (`idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_recordatorio_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `nutri`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`avaliacaoantropometrica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`avaliacaoantropometrica` (
  `idavaliacaoantropometrica` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `dataavaliacao` DATE NOT NULL,
  `altura` FLOAT NOT NULL,
  `pesoatual` FLOAT NOT NULL,
  `pesoideal` FLOAT NOT NULL,
  `bracodireitorelaxado` FLOAT NOT NULL,
  `bracodireitocontraido` FLOAT NOT NULL,
  `antebracodireito` FLOAT NOT NULL,
  `punhodireito` FLOAT NOT NULL,
  `ombro` FLOAT NOT NULL,
  `torax` FLOAT NOT NULL,
  `cintura` FLOAT NOT NULL,
  `abdomen` FLOAT NOT NULL,
  `quadril` FLOAT NOT NULL,
  `panturrilhadireita` FLOAT NOT NULL,
  `coxadireita` FLOAT NOT NULL,
  `coxaproximaldireita` FLOAT NOT NULL,
  `biceps` FLOAT NOT NULL,
  `triceps` FLOAT NOT NULL,
  `subescapular` FLOAT NOT NULL,
  `axilarmedia` FLOAT NOT NULL,
  `toraxica` FLOAT NOT NULL,
  `suprailiaca` FLOAT NOT NULL,
  `abdominal` FLOAT NOT NULL,
  `coxa` FLOAT NOT NULL,
  `panturrilhamedia` FLOAT NOT NULL,
  PRIMARY KEY (`idavaliacaoantropometrica`),
  INDEX `fk_avaliacaoantropometrica_pessoa1_idx` (`idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacaoantropometrica_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `nutri`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`categoriaalimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`categoriaalimentos` (
  `idcategoriaalimentos` INT NOT NULL AUTO_INCREMENT,
  `nomecategoria` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idcategoriaalimentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`alimento` (
  `idalimentos` INT NOT NULL AUTO_INCREMENT,
  `idcategoriaalimentos` INT NOT NULL,
  `nomealimento` VARCHAR(150) NOT NULL,
  `energia` INT NOT NULL,
  `proteina` FLOAT NOT NULL,
  `lipideos` FLOAT NOT NULL,
  `carboidratos` FLOAT NOT NULL,
  PRIMARY KEY (`idalimentos`),
  INDEX `fk_tabelaalimentos_categoriaalimentos1_idx` (`idcategoriaalimentos` ASC) VISIBLE,
  CONSTRAINT `fk_tabelaalimentos_categoriaalimentos1`
    FOREIGN KEY (`idcategoriaalimentos`)
    REFERENCES `nutri`.`categoriaalimentos` (`idcategoriaalimentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`refeicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`refeicao` (
  `idrefeicao` INT NOT NULL AUTO_INCREMENT,
  `nomerefeicao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idrefeicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`pessoa_patologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`pessoa_patologia` (
  `idpessoa` INT NOT NULL,
  `idpatologias` INT NOT NULL,
  PRIMARY KEY (`idpessoa`, `idpatologias`),
  INDEX `fk_pessoa_has_patologias_patologias1_idx` (`idpatologias` ASC) VISIBLE,
  INDEX `fk_pessoa_has_patologias_pessoa1_idx` (`idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_has_patologias_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `nutri`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_has_patologias_patologias1`
    FOREIGN KEY (`idpatologias`)
    REFERENCES `nutri`.`patologia` (`idpatologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutri`.`cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutri`.`cardapio` (
  `idcardapio` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `idalimentos` INT NOT NULL,
  `refeicao_idrefeicao` INT NOT NULL,
  `peso` FLOAT NOT NULL,
  `caloria` FLOAT NOT NULL,
  `proteina` FLOAT NOT NULL,
  `carboidrato` FLOAT NOT NULL,
  `lipideo` FLOAT NOT NULL,
  PRIMARY KEY (`idcardapio`),
  INDEX `fk_pessoa_has_alimento_alimento1_idx` (`idalimentos` ASC) VISIBLE,
  INDEX `fk_pessoa_has_alimento_pessoa1_idx` (`idpessoa` ASC) VISIBLE,
  INDEX `fk_pessoa_has_alimento_refeicao1_idx` (`refeicao_idrefeicao` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_has_alimento_pessoa1`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `nutri`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_has_alimento_alimento1`
    FOREIGN KEY (`idalimentos`)
    REFERENCES `nutri`.`alimento` (`idalimentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_has_alimento_refeicao1`
    FOREIGN KEY (`refeicao_idrefeicao`)
    REFERENCES `nutri`.`refeicao` (`idrefeicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
