INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (2,'Verduras, hortaliças e derivados');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (3,'Frutas e derivados');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (4,'Gorduras e óleos');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (5,'Pescados e frutos do mar');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6,'Carnes e derivados');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (7,'Leite e derivados');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (8,'Bebidas (alcoólicas e não alcoólicas)');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (9,'Ovos e derivados');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (10,'Produtos açucarados');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (11,'Miscelâneas');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (12,'Outros alimentos industrializados');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (13,'Alimentos preparados');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (14,'Leguminosas e derivados');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (15,'Nozes e sementes');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000001,'Cereais e leguminosas');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000002,'Hortaliças tuberosas');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000003,'Farinhas, féculas e massas');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000004,'Cocos, castanhas e nozes');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000005,'Hortaliças folhosas, frutosas e outras');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000006,'Frutas');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000007,'Açúcares e produtos de confeitaria ');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000008,'Sais e condimentos');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000009,'Carnes e vísceras');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000010,'Pescados e frutos do mar');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000011,'Enlatados e conservas');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000012,'Aves e ovos  ');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000013,'Laticínios');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000014,'Panificados');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000015,'Carnes industrializadas');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000016,'Bebidas não alcoólicas e infusões');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000017,'Bebidas alcoólicas');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000018,'Óleos e gorduras');
INSERT INTO nutri.categoriaalimentos (idcategoriaalimento,nomecategoria) VALUES (6000019,'Miscelâneas');
